name: cpp-raycasting
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cmake build
        run: |
          mkdir build
          cd build
          cmake ..
          make
