name: cpp-rpn-calculator
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    container: gcc:13
    steps:
      - uses: actions/checkout@v4
      - name: Install CMake + dependencies
        run: |
          apt update -y
          apt install -y cmake libfmt-dev
      - name: CMake build
        working-directory: ./cpp-fundamentals-exercises/rpn-calculator
        run: |
          mkdir build
          cd build
          cmake ..
          make
